# Generated by Django 4.2.1 on 2023-06-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'Rainbow Fade'), (2, 'Fire'), (3, 'Spectrum'), (4, 'Heart Beat')], default=0),
        ),
    ]
